### ISSUE TITLE
Clothing Recommendation Algorithm

### ISSUE THREAD

**Issue by tykm** [A-Minus-Team/weather-wear#18]
Figure out how to recommend clothing
Take into account the colors of the clothes

**Comment by ezhang123** [comment]
The code has been added to recommend clothes based off color. it cannot be displayed yet until the homepage is further developed but the code template/functions are there, just needs to be called. There could be some improvements to make it more dynamic but also requires the homepage to be further developed prior to that. 

Overall done.
